# .github/dependabot.yml
# A basic configuration for Dependabot to keep project dependencies updated.
# See the full documentation at:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Configuration for Gradle dependency updates
  # This will scan your build.gradle.kts and libs.versions.toml files.
  - package-ecosystem: "gradle"
    directory: "/"  # Location of your root build.gradle.kts
    schedule:
      interval: "weekly" # How often to check for updates (daily, weekly, or monthly)
    open-pull-requests-limit: 10 # Limit the number of open PRs from Dependabot at one time

  # Configuration for GitHub Actions updates
  # This will scan your .github/workflows directory for outdated actions.
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of the .github directory
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
