/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.utilities

import org.example.list.LinkedList

class JoinUtils {
    companion object {
        /**
         * Joins the elements of the provided LinkedList into a single string separated by single spaces.
         *
         * Each element's string representation (via `toString()`) is appended in order. An empty list yields an empty string.
         *
         * @param source LinkedList whose elements will be concatenated.
         * @return A space-delimited string of the list's elements.
         */
        fun join(source: LinkedList): String {
            val result = StringBuilder()
            for (i in 0 until source.size()) {
                if (result.isNotEmpty()) {
                    result.append(" ")
                }
                result.append(source.get(i))
            }

            return result.toString()
        }
    }
import java.util.LinkedList

object JoinUtils {
    /**
     * Joins LinkedList elements into a single string separated by a single space.
     * Preserves whitespace-only and empty elements, handles large lists safely.
     */
    fun join(elements: LinkedList<String>): String = elements.joinToString(separator = " ") { it }
}
