[versions]
# ===== GRADLE & KOTLIN =====
agp = "9.0.0-alpha02"
kotlin = "2.2.20"
ksp = "2.2.0-2.0.2"
googleServices = "4.4.3"
desugar_jdk_libs = "2.1.5"
appcompat = "1.7.1"
composeBom = "2024.10.00"
activityCompose = "1.9.2"
navigationCompose = "2.8.3"
hilt-navigation-compose-version = "1.2.0"
lifecycle = "2.8.4"
roomVersion = "2.6.1"
workManager = "2.10.3"
hiltWork = "1.2.0"
datastore = "1.1.1"
securityCrypto = "1.1.0-alpha06"
benchmark = "1.2.4"
uiAutomator = "2.3.0"

okhttp = "5.1.0"

coilCompose = "2.7.0"

# Utilities & Logging
timber = "5.0.1"
guavaAndroid = "33.2.1-android"
kotlinxCoroutines = "1.8.1"
kotlinxSerializationJson = "1.7.0"
kotlinxDatetime = "0.6.1"
leakcanary = "2.14"
commonsIo = "2.20.0"
commonsCompress = "1.28.0"
xz = "1.10"
slf4j = "2.0.17"

# Unit Testing
junitJupiter = "5.13.4"
mockk = "1.14.5"

# Android Testing
androidxTestJunit = "1.3.0"
espressoCore = "3.7.0"
uiAutomator = "2.3.0"
benchmark = "1.4.1"

# Bouncy Castle
bouncycastle = "1.81"

# Added for app module
freeReflection = "3.2.0"
lsposedLsparanoid = "1.3.1"
highcapableYukiHookAPI = "1.3.1"
# YukiHook
yukiHook = "1.3.1"

# Kotlin Test

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

# Firebase (managed by the BoM)
androidx-rules = { module = "androidx.test:rules", version.ref = "runner" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version = "22.0.1" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version = "26.0.1" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version = "22.0.1" }
firebase-config = { group = "com.google.firebase", name = "firebase-config", version = "23.0.1" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version = "24.0.1" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version = "25.0.1" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version = "23.0.0" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version = "20.0.2" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf", version = "22.0.2" }
firebase-ai = { group = "com.google.firebase", name = "firebase-ai", version = "17.3.0" }

# ===== BUILD PLUGINS =====
openapiGeneratorGradlePlugin = "7.15.0"
firebaseCrashlyticsPlugin = "3.0.6"
firebasePerfPlugin = "2.0.1"
toolchainsFoojayResolver = "1.0.0"
spotless = "7.2.1"
ktlint = "13.1.0"
detektGradlePlugin = "1.23.8"
dokkaGradlePlugin = "2.0.0"



# AndroidX Lifecycle, Room, WorkManager
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeMaterialIconsExtended" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "composeRuntime" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }

# Networking
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
squareup-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }

# UI & Image Loading
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

# Utilities & Logging
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
xz = { group = "org.tukaani", name = "xz", version.ref = "xz" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

# Testing
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.9.2" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiAutomator" }

# Added for app module
freeReflection = { group = "com.github.tiann", name = "FreeReflection", version.ref = "freeReflection" }
lsposed-lsparanoid = { group = "com.github.LSPosed", name = "LSParanoid", version.ref = "lsposedLsparanoid" } # CHANGED

# YukiHook & LSPosed
yukihook-api = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukiHook" }
yukihook-ksp = { group = "com.highcapable.yukihookapi", name = "ksp-xposed", version.ref = "yukiHook" }
# yukihookapi-api-lsposed = { group = "com.github.LSPosed.YukiHookAPI", name = "api", version.ref = "yukiHookAPILSPosed" } # REMOVED
# yukihookapi-processor-lsposed = { group = "com.github.LSPosed.YukiHookAPI", name = "processor", version.ref = "yukiHookAPILSPosed" } # REMOVED


[bundles]
compose-ui = [
    "androidx-compose-ui",
]

compose-debug = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest"
]

coroutines = [
    "kotlinx-coroutines-core",
]

network = [
    "retrofit-core",
    "retrofit-converter-gson",
    "okhttp-core",
    "okhttp-logging-interceptor"
]

lifecycle = [
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-viewmodel-compose"
]

room = [
    "androidx-room-runtime",
    "androidx-room-ktx"
]
testing-unit = [
    "junit4",
    "mockk-android",
    "mockk-agent",
    "kotlinx-coroutines-test",
]

testing-android = [
    "androidx-test-ext-junit",
]




[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# Other plugins
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
