/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.apis

import dev.aurakai.auraframefx.api.client.infrastructure.ApiClient
import dev.aurakai.auraframefx.api.client.infrastructure.ApiResponse
import dev.aurakai.auraframefx.api.client.infrastructure.ClientError
import dev.aurakai.auraframefx.api.client.infrastructure.ClientException
import dev.aurakai.auraframefx.api.client.infrastructure.MultiValueMap
import dev.aurakai.auraframefx.api.client.infrastructure.RequestConfig
import dev.aurakai.auraframefx.api.client.infrastructure.RequestMethod
import dev.aurakai.auraframefx.api.client.infrastructure.ResponseType
import dev.aurakai.auraframefx.api.client.infrastructure.ServerError
import dev.aurakai.auraframefx.api.client.infrastructure.ServerException
import dev.aurakai.auraframefx.api.client.infrastructure.Success
import dev.aurakai.auraframefx.api.client.models.AgentStatus
import okhttp3.Call
import okhttp3.HttpUrl
import java.io.IOException

class AIAgentsApi(
    basePath: kotlin.String = defaultBasePath,
    client: Call.Factory = ApiClient.defaultClient,
) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties()
                .getProperty(ApiClient.baseUrlKey, "https://api.auraframefx.com/v1")
        }
    }

    /**
     * Fetches the status of all AI agents.
     *
     * @return A list of AgentStatus objects representing each agent's status.
     * @throws IllegalStateException If the request configuration is invalid.
     * @throws IOException If an I/O error occurs while performing the HTTP request.
     * @throws UnsupportedOperationException If the API returns an informational or redirection response.
     * @throws ClientException If the API returns a client error response (4xx).
     * @throws ServerException If the API returns a server error response (5xx).
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(
        IllegalStateException::class,
        IOException::class,
        UnsupportedOperationException::class,
        ClientException::class,
        ServerException::class
    )
    fun agentsStatusGet(): kotlin.collections.List<AgentStatus> {
        val localVarResponse = agentsStatusGetWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<AgentStatus>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException(
                    "Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}",
                    localVarError.statusCode,
                    localVarResponse
                )
            }

            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException(
                    "Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}",
                    localVarError.statusCode,
                    localVarResponse
                )
            }
        }
    }

    /**
     * Retrieve the status of all AI agents.
     *
     * Makes a request to the /agents/status endpoint and returns the parsed response.
     *
     * @return ApiResponse<List<AgentStatus>?> containing the list of agent statuses when available.
     * @throws IllegalStateException if the request configuration is invalid.
     * @throws IOException if an I/O error occurs while executing the request.
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun agentsStatusGetWithHttpInfo(): ApiResponse<kotlin.collections.List<AgentStatus>?> {
        val localVariableConfig = agentsStatusGetRequestConfig()

        return request<Unit, kotlin.collections.List<AgentStatus>>(
            localVariableConfig
        )
    }

    /**
     * Build the HTTP request configuration for the GET /agents/status endpoint.
     *
     * The returned RequestConfig targets the path "/agents/status", uses the GET method,
     * sets "Accept" to "application/json", includes an empty query map and no request body,
     * and does not require authentication.
     *
     * @return A RequestConfig<Unit> preconfigured for fetching all AI agents' status.
     */
    fun agentsStatusGetRequestConfig(): RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/agents/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    /**
             * Percent-encodes a single URI path component.
             *
             * @param uriComponent The raw path component to encode.
             * @return The percent-encoded representation of `uriComponent` suitable for use in a URL path segment.
             */
            private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent)
            .build().encodedPathSegments[0]
}