name: Build and Package All APKs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download dependencies and build all modules
      run: ./gradlew assembleDebug

 - name: Upload Build Artifacts
  uses: actions/upload-artifact@v4
  with:
    name: your-artifact-name
    path: path/to/artifacts