on:
  push:

jobs:
  build:
    name: Build & Analyze All Modules
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:

        uses: actions/upload-artifact@v4
        with:

          # Parse JUnit XMLs for test failures
          find ./artifacts -name "*.xml" | while read report; do
            FAILURES=$(grep -E 'failure|error' "$report")
            if [ ! -z "$FAILURES" ]; then
              echo "### Test failures in $report" >> issue-report.md
              grep -E 'failure|error' "$report" | head -10 >> issue-report.md
              echo "" >> issue-report.md
            fi
          done

          # Parse Detekt/ktlint reports for issues
          find ./artifacts -name "detekt.html" | while read detekt; do
            echo "### Detekt issues in $detekt" >> issue-report.md
            grep -i "<span class=\"issue\">" "$detekt" | head -10 >> issue-report.md
            echo "" >> issue-report.md
          done

          # List APK artifacts built
          APK=$(find ./artifacts -name "*.apk" | head -1)
          if [ ! -z "$APK" ]; then
            echo "### APK Built:" >> issue-report.md
            echo "APK Path: $APK" >> issue-report.md
            echo "" >> issue-report.md
          fi

          # If nothing found, add a note
          if ! grep -q "###" issue-report.md; then
            echo "_No build or test issues found in reports._" >> issue-report.md
          fi

      - name: Create/Update Issue with Build Results
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Automated Build/Test Issue Report"
          content-filepath: issue-report.md
          labels: build, report, automated
          assignees: AuraFrameFxDev
          update-existing: true