name: Build and Package All APKs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download dependencies and build all modules
      run: ./gradlew assembleDebug

    - name: Upload all APKs from all modules
      uses: actions/upload-artifact@v3
      with:
        name: all-debug-apks
        path: '**/build/outputs/apk/debug/*.apk'
